"""
SVG Converter Module
تحويل الصور إلى صيغة SVG

SVG conversion with professional quality and support for multiple formats
"""

import os
import base64
from pathlib import Path
from PIL import Image
from i18n import tr


class SVGConverter:
    """تحويل الصور إلى SVG / Convert images to SVG format"""

    def __init__(self, export_folder="exports"):
        """
        Initialize SVGConverter

        Args:
            export_folder: مجلد الحفظ / Output folder path
        """
        self.export_folder = export_folder
        Path(export_folder).mkdir(parents=True, exist_ok=True)

    def convert_to_svg(self, image_path: str, method: str = "raster") -> tuple:
        """
        تحويل الصورة إلى SVG

        Convert image to SVG format

        Args:
            image_path: مسار الصورة الأصلية / Path to original image
            method: طريقة التحويل - 'raster' أو 'vector' / Conversion method

        Returns:
            tuple: (success: bool, message: str, output_path: str)
        """
        try:
            file_name = Path(image_path).stem
            output_path = os.path.join(self.export_folder, f"{file_name}.svg")

            # الحصول على حجم الصورة / Get image dimensions
            with Image.open(image_path) as img:
                width, height = img.size

            # قراءة الصورة وتحويلها إلى base64 / Read and encode image
            with open(image_path, "rb") as img_file:
                encoded = base64.b64encode(img_file.read()).decode()

            # تحديد نوع الصورة / Determine image type
            img_format = Path(image_path).suffix.lower()[1:]
            if img_format in ['jpg', 'jpeg']:
                mime_type = "image/jpeg"
            elif img_format == 'gif':
                mime_type = "image/gif"
            elif img_format == 'bmp':
                mime_type = "image/bmp"
            else:
                mime_type = "image/png"

            # إنشاء محتوى SVG / Create SVG content
            svg_content = self._create_svg_wrapper(
                encoded,
                width,
                height,
                mime_type,
                file_name
            )

            # حفظ ملف SVG / Save SVG file
            with open(output_path, "w", encoding="utf-8") as svg_file:
                svg_file.write(svg_content)

            return True, tr("msg_saved_svg") + output_path, output_path

        except Exception as e:
            error_msg = f"{tr('msg_save_error')}{str(e)}"
            return False, error_msg, None

    def _create_svg_wrapper(self, base64_data: str, width: int, height: int,
                           mime_type: str, filename: str) -> str:
        """
        إنشاء محتوى SVG يغلف الصورة

        Create SVG wrapper content

        Args:
            base64_data: البيانات المشفرة / Encoded image data
            width: عرض الصورة / Image width
            height: ارتفاع الصورة / Image height
            mime_type: نوع MIME للصورة / MIME type
            filename: اسم الملف الأساسي / Base filename

        Returns:
            str: محتوى SVG / SVG content
        """
        svg = f'''<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
     width="{width}" height="{height}" viewBox="0 0 {width} {height}">
  <defs>
    <style type="text/css">
      <![CDATA[
        /* Generated by Iconora Studio */
        image {{ image-rendering: crisp-edges; }}
      ]]>
    </style>
  </defs>
  <!-- Image: {filename} -->
  <image xlink:href="data:{mime_type};base64,{base64_data}"
         x="0" y="0" width="{width}" height="{height}" />
</svg>'''
        return svg

    def batch_convert_to_svg(self, image_paths: list) -> dict:
        """
        تحويل عدة صور إلى SVG دفعة واحدة

        Batch convert multiple images to SVG

        Args:
            image_paths: قائمة مسارات الصور / List of image paths

        Returns:
            dict: النتائج للملفات المختلفة / Results dictionary
        """
        results = {
            "success": [],
            "failed": [],
            "total": len(image_paths)
        }

        for img_path in image_paths:
            success, message, output_path = self.convert_to_svg(img_path)
            if success:
                results["success"].append({
                    "input": img_path,
                    "output": output_path,
                    "message": message
                })
            else:
                results["failed"].append({
                    "input": img_path,
                    "error": message
                })

        return results

    def get_svg_info(self, svg_path: str) -> dict:
        """
        الحصول على معلومات ملف SVG

        Get SVG file information

        Args:
            svg_path: مسار ملف SVG / SVG file path

        Returns:
            dict: معلومات الملف / File information
        """
        try:
            if not os.path.exists(svg_path):
                return {"error": f"{tr('msg_file_error')}{svg_path}"}

            file_size = os.path.getsize(svg_path)
            return {
                "path": svg_path,
                "filename": os.path.basename(svg_path),
                "size_bytes": file_size,
                "size_kb": round(file_size / 1024, 2),
                "exists": True
            }
        except Exception as e:
            return {"error": str(e)}
